#!/bin/sh



# Suggestions for improvments:
#
# 1. MUMPS vs UMFPACK gives skewed results (MUMPS faster?)
# 2. Run on 128 x 128 x 128
# 3. Time assemble_cells and apply separately
# 4. Time solve separately
# 5. Use barriers between timings

./analyse-bench | grep -v Reading
