// Copyright (C) 2007 Anders Logg.
// Licensed under the GNU LGPL Version 2.1.
//
// Modifies by Garth N. Wells, 2007.
//
// First added:  2007-01-17
// Last changed: 2007-04-30

#ifndef __DOF_MAPS_H
#define __DOF_MAPS_H

#include <map>
#include <vector>
#include <string>
#include <ufc.h>

#include <dolfin/constants.h>

namespace dolfin
{

  class DofMap;
  class Mesh;
  class SparsityPattern;
  class UFC;

  /// This class provides storage and caching of (precomputed) dof
  /// maps and enables reuse of already computed dof maps with equal
  /// signatures.

  class DofMaps
  {
  public:
    
    /// Create empty set of dof maps
    DofMaps();

    /// Destructor
    ~DofMaps();

    /// Update set of dof maps for given form
    void update(const ufc::form& form, Mesh& mesh);
    
    /// Return number of dof maps
    uint size() const;
    
    /// Return dof map for argument function i
    const DofMap& operator[] (uint i) const;
    
    /// Compute sparsity pattern generated by two maps
    void sparsityPattern(SparsityPattern& sparsity_pattern, Mesh& mesh, UFC& ufc) const;

  private:

    // Cached precomputed dof maps
    std::map<const std::string, std::pair<ufc::dof_map*, DofMap*> > dof_map_cache;

    // Array of dof maps for current form
    std::vector<DofMap*> dof_maps;

    // Iterator for map
    typedef std::map<const std::string, std::pair<ufc::dof_map*, DofMap*> >::iterator map_iterator;

    /// Compute sparsity pattern for a scalar
    void scalarSparsityPattern(SparsityPattern& sparsity_pattern) const;

    /// Compute sparsity pattern for a vector
    void vectorSparsityPattern(SparsityPattern& sparsity_pattern) const;

    /// Compute sparsity pattern generated by two maps (for a matrix)
    void matrixSparsityPattern(SparsityPattern& sparsity_pattern, Mesh& mesh, UFC& ufc) const;

  };

}

#endif
