// Copyright (C) 2007 Anders Logg.
// Licensed under the GNU GPL Version 2.
//
// First added:  2007-04-02
// Last changed: 2007-04-02

#ifndef __NEW_FORM_H
#define __NEW_FORM_H

#include <ufc.h>

#include <dolfin/Array.h>
#include <dolfin/Function.h>

namespace dolfin
{

  /// Base class for UFC code generated by FFC for DOLFIN with option -l

  // FIXME: Rename to Form when old form system has been removed

  class NewForm
  {
  public:

    /// Destructor
    virtual ~NewForm() {}

    /// Return UFC form
    virtual const ufc::form& form() const = 0;

    /// Return array of coefficients
    virtual const Array<Function*>& coefficients() const = 0;

  };

}

#endif
