// Copyright (C) 2007 Anders Logg.
// Licensed under the GNU GPL Version 2.
//
// First added:  2007-01-01
// Last changed: 2007-01-01

#ifndef __NEW_FORM_H
#define __NEW_FORM_H

#include <dolfin/Array.h>
#include <dolfin/Function.h>

namespace dolfin
{

  /// Base class for UFC code generated by FFC for DOLFIN with option -l

  // FIXME: Rename to Form when old form system has been removed

  class NewForm
  {
  public:

    /// Array of coefficients
    Array<Function*> coefficients;

  };

}

#endif
