// Automatically generated by FFC, the FEniCS Form Compiler, version 0.2.5.
// For further information, go to http://www/fenics.org/ffc/.
// Licensed under the GNU GPL Version 2.

#ifndef __P4TET_H
#define __P4TET_H

#include <dolfin/Mesh.h>
#include <dolfin/Cell.h>
#include <dolfin/Point.h>
#include <dolfin/Vector.h>
#include <dolfin/AffineMap.h>
#include <dolfin/FiniteElement.h>
#include <dolfin/FiniteElementSpec.h>

namespace dolfin
{
  
  class P4tet : public dolfin::FiniteElement
  {
  public:
  
    P4tet() : dolfin::FiniteElement(), tensordims(0), subelements(0)
    {
      // Element is scalar, don't need to initialize tensordims
  
      // Element is simple, don't need to initialize subelements
    }
  
    ~P4tet()
    {
      if ( tensordims ) delete [] tensordims;
      if ( subelements )
      {
        for (unsigned int i = 0; i < elementdim(); i++)
          delete subelements[i];
        delete [] subelements;
      }
    }
  
    inline unsigned int spacedim() const
    {
      return 35;
    }
  
    inline unsigned int shapedim() const
    {
      return 3;
    }
  
    inline unsigned int tensordim(unsigned int i) const
    {
      dolfin_error("Element is scalar.");
      return 0;
    }
  
    inline unsigned int elementdim() const
    {
      return 1;
    }
  
    inline unsigned int rank() const
    {
      return 0;
    }
  
    void nodemap(int nodes[], const Cell& cell, const Mesh& mesh) const
    {
      static unsigned int edge_reordering_0[2][3] = {{0, 1, 2}, {2, 1, 0}};
      static unsigned int face_reordering_0[6][3] = {{0, 1, 2}, {0, 2, 1}, {2, 0, 1}, {1, 0, 2}, {1, 2, 0}, {2, 1, 0}};
      nodes[0] = cell.vertexID(0);
      nodes[1] = cell.vertexID(1);
      nodes[2] = cell.vertexID(2);
      nodes[3] = cell.vertexID(3);
      int alignment = cell.edgeAlignment(0);
      int offset = mesh.numVertices();
      nodes[4] = offset + 3*cell.edgeID(0) + edge_reordering_0[alignment][0];
      nodes[5] = offset + 3*cell.edgeID(0) + edge_reordering_0[alignment][1];
      nodes[6] = offset + 3*cell.edgeID(0) + edge_reordering_0[alignment][2];
      alignment = cell.edgeAlignment(1);
      nodes[7] = offset + 3*cell.edgeID(1) + edge_reordering_0[alignment][0];
      nodes[8] = offset + 3*cell.edgeID(1) + edge_reordering_0[alignment][1];
      nodes[9] = offset + 3*cell.edgeID(1) + edge_reordering_0[alignment][2];
      alignment = cell.edgeAlignment(2);
      nodes[10] = offset + 3*cell.edgeID(2) + edge_reordering_0[alignment][0];
      nodes[11] = offset + 3*cell.edgeID(2) + edge_reordering_0[alignment][1];
      nodes[12] = offset + 3*cell.edgeID(2) + edge_reordering_0[alignment][2];
      alignment = cell.edgeAlignment(3);
      nodes[13] = offset + 3*cell.edgeID(3) + edge_reordering_0[alignment][0];
      nodes[14] = offset + 3*cell.edgeID(3) + edge_reordering_0[alignment][1];
      nodes[15] = offset + 3*cell.edgeID(3) + edge_reordering_0[alignment][2];
      alignment = cell.edgeAlignment(4);
      nodes[16] = offset + 3*cell.edgeID(4) + edge_reordering_0[alignment][0];
      nodes[17] = offset + 3*cell.edgeID(4) + edge_reordering_0[alignment][1];
      nodes[18] = offset + 3*cell.edgeID(4) + edge_reordering_0[alignment][2];
      alignment = cell.edgeAlignment(5);
      nodes[19] = offset + 3*cell.edgeID(5) + edge_reordering_0[alignment][0];
      nodes[20] = offset + 3*cell.edgeID(5) + edge_reordering_0[alignment][1];
      nodes[21] = offset + 3*cell.edgeID(5) + edge_reordering_0[alignment][2];
      alignment = cell.faceAlignment(0);
      offset = offset + 3*mesh.numEdges();
      nodes[22] = offset + 3*cell.faceID(0) + face_reordering_0[alignment][0];
      nodes[23] = offset + 3*cell.faceID(0) + face_reordering_0[alignment][1];
      nodes[24] = offset + 3*cell.faceID(0) + face_reordering_0[alignment][2];
      alignment = cell.faceAlignment(1);
      nodes[25] = offset + 3*cell.faceID(1) + face_reordering_0[alignment][0];
      nodes[26] = offset + 3*cell.faceID(1) + face_reordering_0[alignment][1];
      nodes[27] = offset + 3*cell.faceID(1) + face_reordering_0[alignment][2];
      alignment = cell.faceAlignment(2);
      nodes[28] = offset + 3*cell.faceID(2) + face_reordering_0[alignment][0];
      nodes[29] = offset + 3*cell.faceID(2) + face_reordering_0[alignment][1];
      nodes[30] = offset + 3*cell.faceID(2) + face_reordering_0[alignment][2];
      alignment = cell.faceAlignment(3);
      nodes[31] = offset + 3*cell.faceID(3) + face_reordering_0[alignment][0];
      nodes[32] = offset + 3*cell.faceID(3) + face_reordering_0[alignment][1];
      nodes[33] = offset + 3*cell.faceID(3) + face_reordering_0[alignment][2];
      offset = offset + 3*mesh.numFaces();
      nodes[34] = offset + cell.id();
    }
  
    void pointmap(Point points[], unsigned int components[], const AffineMap& map) const
    {
      points[0] = map(0.000000000000000e+00, 0.000000000000000e+00, 0.000000000000000e+00);
      points[1] = map(1.000000000000000e+00, 0.000000000000000e+00, 0.000000000000000e+00);
      points[2] = map(0.000000000000000e+00, 1.000000000000000e+00, 0.000000000000000e+00);
      points[3] = map(0.000000000000000e+00, 0.000000000000000e+00, 1.000000000000000e+00);
      points[4] = map(7.500000000000000e-01, 2.500000000000000e-01, 0.000000000000000e+00);
      points[5] = map(5.000000000000000e-01, 5.000000000000000e-01, 0.000000000000000e+00);
      points[6] = map(2.500000000000000e-01, 7.500000000000000e-01, 0.000000000000000e+00);
      points[7] = map(0.000000000000000e+00, 7.500000000000000e-01, 0.000000000000000e+00);
      points[8] = map(0.000000000000000e+00, 5.000000000000000e-01, 0.000000000000000e+00);
      points[9] = map(0.000000000000000e+00, 2.500000000000000e-01, 0.000000000000000e+00);
      points[10] = map(2.500000000000000e-01, 0.000000000000000e+00, 0.000000000000000e+00);
      points[11] = map(5.000000000000000e-01, 0.000000000000000e+00, 0.000000000000000e+00);
      points[12] = map(7.500000000000000e-01, 0.000000000000000e+00, 0.000000000000000e+00);
      points[13] = map(0.000000000000000e+00, 0.000000000000000e+00, 2.500000000000000e-01);
      points[14] = map(0.000000000000000e+00, 0.000000000000000e+00, 5.000000000000000e-01);
      points[15] = map(0.000000000000000e+00, 0.000000000000000e+00, 7.500000000000000e-01);
      points[16] = map(7.500000000000000e-01, 0.000000000000000e+00, 2.500000000000000e-01);
      points[17] = map(5.000000000000000e-01, 0.000000000000000e+00, 5.000000000000000e-01);
      points[18] = map(2.500000000000000e-01, 0.000000000000000e+00, 7.500000000000000e-01);
      points[19] = map(0.000000000000000e+00, 7.500000000000000e-01, 2.500000000000000e-01);
      points[20] = map(0.000000000000000e+00, 5.000000000000000e-01, 5.000000000000000e-01);
      points[21] = map(0.000000000000000e+00, 2.500000000000000e-01, 7.500000000000000e-01);
      points[22] = map(5.000000000000000e-01, 2.500000000000000e-01, 2.500000000000000e-01);
      points[23] = map(2.500000000000000e-01, 2.500000000000000e-01, 5.000000000000000e-01);
      points[24] = map(2.500000000000000e-01, 5.000000000000000e-01, 2.500000000000000e-01);
      points[25] = map(0.000000000000000e+00, 5.000000000000000e-01, 2.500000000000000e-01);
      points[26] = map(0.000000000000000e+00, 2.500000000000000e-01, 5.000000000000000e-01);
      points[27] = map(0.000000000000000e+00, 2.500000000000000e-01, 2.500000000000000e-01);
      points[28] = map(2.500000000000000e-01, 0.000000000000000e+00, 5.000000000000000e-01);
      points[29] = map(5.000000000000000e-01, 0.000000000000000e+00, 2.500000000000000e-01);
      points[30] = map(2.500000000000000e-01, 0.000000000000000e+00, 2.500000000000000e-01);
      points[31] = map(2.500000000000000e-01, 2.500000000000000e-01, 0.000000000000000e+00);
      points[32] = map(5.000000000000000e-01, 2.500000000000000e-01, 0.000000000000000e+00);
      points[33] = map(2.500000000000000e-01, 5.000000000000000e-01, 0.000000000000000e+00);
      points[34] = map(2.500000000000000e-01, 2.500000000000000e-01, 2.500000000000000e-01);
      components[0] = 0;
      components[1] = 0;
      components[2] = 0;
      components[3] = 0;
      components[4] = 0;
      components[5] = 0;
      components[6] = 0;
      components[7] = 0;
      components[8] = 0;
      components[9] = 0;
      components[10] = 0;
      components[11] = 0;
      components[12] = 0;
      components[13] = 0;
      components[14] = 0;
      components[15] = 0;
      components[16] = 0;
      components[17] = 0;
      components[18] = 0;
      components[19] = 0;
      components[20] = 0;
      components[21] = 0;
      components[22] = 0;
      components[23] = 0;
      components[24] = 0;
      components[25] = 0;
      components[26] = 0;
      components[27] = 0;
      components[28] = 0;
      components[29] = 0;
      components[30] = 0;
      components[31] = 0;
      components[32] = 0;
      components[33] = 0;
      components[34] = 0;
    }
  
    void vertexeval(real values[], unsigned int vertex, const real x[], const Mesh& mesh) const
    {
      // FIXME: Temporary fix for Lagrange elements
      values[0] = x[vertex];
    }
  
    const FiniteElement& operator[] (unsigned int i) const
    {
      return *this;
    }
  
    FiniteElement& operator[] (unsigned int i)
    {
      return *this;
    }
  
    FiniteElementSpec spec() const
    {
      FiniteElementSpec s("Lagrange", "tetrahedron", 4);
      return s;
    }
    
  private:
  
    unsigned int* tensordims;
    FiniteElement** subelements;
  
  };
  
}

#endif
