// Copyright (C) 2008 Anders Logg.
// Licensed under the GNU LGPL Version 2.1.
//
// Modified by Magnus Vikstrøm, 2008
//
// First added:  2008-01-11
// Last changed: 2008-01-15

#ifndef __P_FORM_H
#define __P_FORM_H

#include <ufc.h>

#include <dolfin/Array.h>
#include <dolfin/pDofMapSet.h>
#include <dolfin/Function.h>

namespace dolfin
{

  /// Base class for UFC code generated by FFC for DOLFIN with option -l

  class pForm
  {
  public:

    /// Constructor
    pForm() : dof_map_set(0), local_dof_map_set(false) {}

    /// Destructor
    virtual ~pForm();

    /// Return UFC form
    virtual const ufc::form& form() const = 0;

    /// Return array of coefficients
    virtual const Array<Function*>& coefficients() const = 0;

    /// Create degree of freedom maps 
    void updateDofMaps(Mesh& mesh, MeshFunction<uint>& partitions);

    /// Set degree of freedom maps
    void setDofMaps(pDofMapSet& dof_map_set);

    /// Return pDofMapSet
    pDofMapSet& dofMaps() const;

  private:

    // Degree of freedom maps
    pDofMapSet* dof_map_set;

    // Local degree of freedom maps (locally owned)
    pDofMapSet* local_dof_map_set;

  };

}

#endif
