# Copyright (C) 2026 Jack S. Hale
#
# This file is part of DOLFINx (https://www.fenicsproject.org)
#
# SPDX-License-Identifier:    LGPL-3.0-or-later
"""High-level problem classes using native linear algebra objects.

Users with advanced requirements should use PETSc.
"""

from collections.abc import Sequence

import numpy.typing as npt

import ufl
from dolfinx.fem import (
    DirichletBC,
    Form,
    Function,
    apply_lifting,
    assemble_matrix,
    assemble_vector,
    create_matrix,
    create_vector,
    form,
)
from dolfinx.la import InsertMode, MatrixCSR, Vector
from dolfinx.la.superlu_dist import superlu_dist_matrix, superlu_dist_solver
from dolfinx.mesh import EntityMap as EntityMap

__all__ = ["LinearProblem"]


class LinearProblem:
    r"""High-level class for solving linear problems using SuperLU_DIST.

    Solves problems of the form :math:`a(u, v) = f(v) \\forall v \\in V`
    using SuperLU_DIST as the linear solver.
    """

    def __init__(
        self,
        a: ufl.Form,
        L: ufl.Form,
        bcs: Sequence[DirichletBC] | None = None,
        u: Function | None = None,
        form_compiler_options: dict | None = None,
        dtype: npt.DTypeLike = None,
        jit_options: dict | None = None,
        entity_maps: Sequence[EntityMap] | None = None,
    ) -> None:
        """Initialize SuperLU_DIST solver for a linear variational problem.

        Args:
            a: Bilinear UFL form, the left-hand side of the variational
               problem.
            L: Linear UFL form, the right-hand side of the variational
               problem.
            bcs: Sequence of Dirichlet boundary conditions to apply to
                 the variational problem.
            u: Solution function. It is created if not provided.
            dtype: dtype passed to FFCx for form compilation. Must match
               dtype of ``u``, if passed.
            form_compiler_options: Options used in FFCx compilation of
                all forms. Run ``ffcx --help`` at the commandline to see
                all available options.
            jit_options: Options used in CFFI JIT compilation of C
                code generated by FFCx. See ``python/dolfinx/jit.py`` for
                all available options. Takes priority over all other
                option values.
            entity_maps: If any trial functions, test functions, or
                coefficients in the form are not defined over the same mesh
                as the integration domain, a corresponding :class:
                `EntityMap<dolfinx.mesh.EntityMap>` must be provided.
        """
        self._a = form(
            a,
            dtype,
            form_compiler_options=form_compiler_options,
            jit_options=jit_options,
            entity_maps=entity_maps,
        )
        self._L = form(
            L,
            dtype,
            form_compiler_options=form_compiler_options,
            jit_options=jit_options,
            entity_maps=entity_maps,
        )
        self._A = create_matrix(self._a)
        self._x = create_vector(L.arguments()[0].ufl_function_space(), dtype=dtype)
        self._b = create_vector(L.arguments()[0].ufl_function_space(), dtype=dtype)

        self._u: Function
        if u is None:
            self._u = Function(L.arguments()[0].ufl_function_space(), dtype=dtype)
        else:
            assert u.dtype == dtype
            self._u = u

        self.bcs = [] if bcs is None else bcs

    def solve(self) -> Function:
        """Solve the problem.

        This method updates the solution ``u`` function(s) stored in the
        problem instance.

        Returns:
            The solution function(s).
        """
        # Assemble lhs
        self.A.set_value(0.0)
        assemble_matrix(self.A, self.a, bcs=self.bcs)
        self.A.scatter_reverse()

        # Recall that using SuperLU_DIST requires a deep copy of data in A,
        # and solving overwrites that deep copy data in-place.
        A_superlu_dist = superlu_dist_matrix(self.A)
        solver = superlu_dist_solver(A_superlu_dist)

        # Assemble rhs
        self.b.array[:] = 0.0
        assemble_vector(self.b.array, self.L)

        # Apply boundary conditions to the rhs
        if self.bcs is not None:
            apply_lifting(self.b.array, [self.a], bcs=[self.bcs])
            self.b.scatter_reverse(InsertMode.add)
            for bc in self.bcs:
                bc.set(self.b.array)
        else:
            self.b.scatter_forward()

        # Solve linear system and update ghost values in the solution
        solver.solve(self.b, self.x)
        self.x.scatter_forward()
        self.u.x.array[:] = self.x.array
        return self.u

    @property
    def L(self) -> Form:
        """The compiled linear form representing the left-hand side."""
        return self._L

    @property
    def a(self) -> Form:
        """The compiled bilinear form representing the right-hand side."""
        return self._a

    @property
    def A(self) -> MatrixCSR:
        """Left-hand side matrix."""
        return self._A

    @property
    def b(self) -> Vector:
        """Right-hand side vector."""
        return self._b

    @property
    def x(self) -> Vector:
        """Solution vector.

        Note:
            The vector does not share memory with the solution
            function ``u``.
        """
        return self._x

    @property
    def u(self) -> Function:
        """Solution function(s).

        Note:
            The function do not share memory with the solution
            vector ``x``.
        """
        return self._u
