#!/bin/sh

# This script uses doxygen to create documentation.

# Simple test to see where we are
# FIXME: Does not work when typing ./scripts/...
CHECK=`echo $0 | cut -d'/' -f1`
if [ "$CHECK" != "scripts" ]; then
    echo "This script must be run from the top level directory."
    exit 1
fi

# Run doxygen
/usr/bin/doxygen doc/progr_reference/html/Doxyfile
