#!/usr/bin/env python

"""This script provides a benchmark for interpolation between meshes"""

# Copyright (C) 2013 Anders Logg
#
# This file is part of DOLFIN.
#
# DOLFIN is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# DOLFIN is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with DOLFIN. If not, see <http://www.gnu.org/licenses/>.
#
# First added:  2013-06-17
# Last changed: 2013-06-21

from dolfin import *
from time import time

SIZE_0 = 21 #71
SIZE_1 = 23 #73

info("Extrapolation from P1 on UnitCubeMesh(%d, %d, %d) to "
     "P1 on UnitCubeMesh(%d, %d, %d)"
     % (SIZE_0, SIZE_0, SIZE_0, SIZE_1, SIZE_1, SIZE_1))

parameters["allow_extrapolation"] = True

mesh_0 = UnitCubeMesh(SIZE_0, SIZE_0, SIZE_0)
mesh_1 = UnitCubeMesh(SIZE_1, SIZE_1, SIZE_1)

V0 = FunctionSpace(mesh_0, "CG", 1)
V1 = FunctionSpace(mesh_1, "CG", 1)

v0 = interpolate(Expression("sin(5*x[0])*cos(7*x[1])"), V0)

tic = time()
v1 = interpolate(v0, V1)
t = time() - tic

print "BENCH: ", t
