#!/usr/bin/env python
#
# Copyright (C) 2008 Anders Logg
#
# This file is part of DOLFIN.
#
# DOLFIN is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# DOLFIN is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with DOLFIN. If not, see <http://www.gnu.org/licenses/>.
#
# Script for ordering a DOLFIN mesh according to the UFC ordering scheme

import sys, os, shutil

from dolfin import Mesh, File

def main(args):
    "Main function"

    # Check that we got at least
    if not len(args) > 0:
        usage()
        sys.exit(2)

    # Convert each mesh
    for filename in args:
        print "Ordering %s" % filename

        # Read and order mesh
        mesh = Mesh(filename)
        mesh.order()

        # Make backup copy
        shutil.move(filename, filename + ".bak")

        # Write file and gzip if necessary
        gzip = False
        if len(filename) >= 3 and filename[-3:] == ".gz":
            filename = filename[:-3]
            gzip = True
        file = File(filename)
        file << mesh
        if gzip:
            os.system("gzip " + filename)

def usage():
    "Print usage instructions"
    print "Usage: dolfin-order mesh0.xml[.gz] [mesh1.xml[.gz] mesh2.xml[.gz] ...]"

if __name__ == "__main__":
    main(sys.argv[1:])
