"""
FiniteElement("Lagrange", "triangle", 1)
FiniteElement("Lagrange", "triangle", 2)
FiniteElement("Lagrange", "triangle", 3)
FiniteElement("Lagrange", "tetrahedron", 1)
FiniteElement("Lagrange", "tetrahedron", 2)
FiniteElement("Lagrange", "tetrahedron", 3)
FiniteElement("Discontinuous Lagrange", "triangle", 0)
FiniteElement("Discontinuous Lagrange", "triangle", 1)
FiniteElement("Discontinuous Lagrange", "triangle", 2)
FiniteElement("Discontinuous Lagrange", "tetrahedron", 0)
FiniteElement("Discontinuous Lagrange", "tetrahedron", 1)
FiniteElement("Discontinuous Lagrange", "tetrahedron", 2)
FiniteElement("Discontinuous Lagrange", "tetrahedron", 3)
VectorElement("Lagrange", "triangle", 1)
VectorElement("Lagrange", "triangle", 2)
VectorElement("Lagrange", "triangle", 3)
VectorElement("Lagrange", "tetrahedron", 1)
VectorElement("Lagrange", "tetrahedron", 2)
VectorElement("Lagrange", "tetrahedron", 3)
VectorElement("Discontinuous Lagrange", "triangle", 0)
VectorElement("Discontinuous Lagrange", "triangle", 1)
VectorElement("Discontinuous Lagrange", "triangle", 2)
VectorElement("Discontinuous Lagrange", "tetrahedron", 0)
VectorElement("Discontinuous Lagrange", "tetrahedron", 1)
VectorElement("Discontinuous Lagrange", "tetrahedron", 2)
VectorElement("Discontinuous Lagrange", "tetrahedron", 3)
FiniteElement("Brezzi-Douglas-Marini", "triangle", 1)
"""
