#!/bin/sh
#
# This script runs all the others.

echo "The following scripts will now be run:"
echo ""
echo "  cmake/scripts/generate-form-files"
echo "  cmake/scripts/generate-demo-files"
echo "  cmake/scripts/generate-cmakefiles"
echo "  cmake/scripts/generate-swig-docstrings"
echo "  cmake/scripts/generate-swig-interface"
echo "  cmake/scripts/download-demo-data"
echo ""
echo "Press return to continue."
read x

./cmake/scripts/generate-form-files
./cmake/scripts/generate-demo-files
./cmake/scripts/generate-cmakefiles
./cmake/scripts/generate-swig-docstrings
./cmake/scripts/generate-swig-interface
./cmake/scripts/download-demo-data
