#!/bin/bash
source /usr/local/dolfinx-complex/share/dolfinx/dolfinx.conf
export PETSC_ARCH=linux-gnu-complex-32
export PYTHONPATH=/usr/local/lib/dolfinx-complex/lib/python3.8/dist-packages:$PYTHONPATH
