# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import datetime
import importlib.metadata
import os
import sys

import mpi4py

import numpy as np
import packaging

import basix
import ffcx
import ufl

sys.path.insert(0, os.path.abspath("."))
import jupytext_process  # isort:skip


myst_heading_anchors = 3

jupytext_process.process()

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.mathjax",
    "sphinx.ext.napoleon",
    "sphinx.ext.todo",
    "sphinx.ext.viewcode",
    "myst_parser",
    "sphinx_codeautolink",
    "sphinx.ext.intersphinx",
    "sphinxcontrib.bibtex",
]

# Bibligraphy file
bibtex_bibfiles = ["refs.bib"]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "DOLFINx Python"
now = datetime.datetime.now()
date = now.date()
copyright = f"{date.year}, FEniCS Project"
author = "FEniCS Project"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = importlib.metadata.version("fenics-dolfinx")
release = version

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "pydata_sphinx_theme"
html_title = f"DOLFINx Python {release}"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = []

# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "DOLFINxdoc"


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, "DOLFIN.tex", "DOLFINx Documentation", "FEniCS Project", "manual"),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, "dolfinx", "DOLFINx Documentation", [author], 1)]

autodoc_default_options = {
    "members": True,
    "show-inheritance": True,
    "imported-members": True,
    "undoc-members": True,
}
autosummary_generate = True
autosummary_ignore_module_all = False
autoclass_content = "both"

codeautolink_concat_default = True

intersphinx_resolve_self = "dolfinx"

# Could be reimplemented using packaging.version
basix_version = "main" if "dev0" in basix.__version__ else "v" + basix.__version__
ffcx_version = "main" if "dev0" in ffcx.__version__ else "v" + ffcx.__version__
ufl_version = "main" if "dev0" in ufl.__version__ else ufl.__version__

numpy_version = packaging.version.parse(np.__version__)
numpy_doc_version = f"{numpy_version.major}.{numpy_version.minor}"

# Note that as of late 2025 pyvista and petsc4py only have docs for the latest
# releases.
intersphinx_mapping = {
    "petsc4py": (
        "https://petsc.org/release/petsc4py",
        None,
    ),
    "numpy": (
        f"https://numpy.org/doc/{numpy_doc_version}",
        None,
    ),
    "pyvista": (
        "https://docs.pyvista.org",
        None,
    ),
    "mpi4py": (
        f"https://mpi4py.readthedocs.io/en/{mpi4py.__version__}",
        None,
    ),
    "python": (
        "https://docs.python.org/3",
        None,
    ),
    "scipy": (
        "https://docs.scipy.org/doc/scipy",
        None,
    ),
    "numba": (
        "https://numba.readthedocs.io/en/stable",
        None,
    ),
    "basix": (
        f"https://docs.fenicsproject.org/basix/{basix_version}/python",
        None,
    ),
    "ffcx": (
        f"https://docs.fenicsproject.org/ffcx/{ffcx_version}",
        None,
    ),
    "ufl": (
        f"https://docs.fenicsproject.org/ufl/{ufl_version}",
        None,
    ),
}

napoleon_google_docstring = True
napoleon_use_admonition_for_notes = False

myst_enable_extensions = [
    "dollarmath",
]

# Fail the build on an unresolvable :doc:/{py:*} target, e.g. a typo or a
# renamed API, rather than silently rendering it as plain text.
nitpicky = True

# Targets that are real but that cannot be made to resolve: live
# attributes/methods of an external project (ufl) that project's own
# docs do not publish, and dolfinx module attributes bound directly at
# the nanobind layer (plain values, not introspectable Python
# descriptors), which autodoc cannot discover as documented py:data
# targets.
nitpick_ignore = [
    ("py:attr", "ufl.Mesh.geometric_dimension"),
    ("py:obj", "ufl.dP"),
    ("py:obj", "ufl.dr"),
    ("py:class", "ufl.MixedFunctionSpace"),
    ("py:func", "ufl.TrialFunctions"),
    ("py:data", "dolfinx.has_parmetis"),
    ("py:data", "dolfinx.has_ptscotch"),
    ("py:data", "dolfinx.has_kahip"),
]

# Categories of target that can never resolve, matched by pattern. The
# role autodoc picks for the same annotation atom is not always stable
# (observed both py:class and py:obj for the same TypeVar depending on
# where in a docstring/signature it is rendered), so most patterns match
# any role rather than hard-coding one.
#
# - numpy scalar types (numpy.int32, ...) are documented upstream as an
#   'attribute', and numpy.typing.NDArray/DTypeLike/ArrayLike as 'data',
#   so an annotation-derived py:class xref never matches either -- in
#   both their canonical form and the private path
#   (numpy._typing._array_like.NDArray, ...) that typing.get_type_hints
#   resolves them to, or the bare `np.`/`npt.` import-alias form that
#   autodoc renders when it cannot fully evaluate a surrounding
#   self-referential generic annotation (observed for mpi4py, scipy and
#   petsc4py aliases too: `_MPI.Comm`, `_sparse.csr_matrix`,
#   `PETSc.Vec`/`Mat`, all real, resolvable public names once qualified,
#   which Sphinx never does automatically);
# - nanobind renders a bound C++ function's array/tuple parameters as a
#   literal structural type string (e.g. `numpy.ndarray[dtype=int32,
#   writable=False]`), not a nominal dotted path, which can never
#   resolve as a cross-reference;
# - basix's own element class hierarchy (basix.ufl._BasixElement and
#   siblings) and the concrete, per-dtype nanobind classes bound at
#   dolfinx's and basix's C++ layer are real types that legitimately
#   appear in public type signatures, but have no public class name to
#   document;
# - dolfinx's own internal TypeVars/type aliases (dolfinx/typing.py,
#   mesh.py, fem/petsc.py, la.py, la/superlu_dist.py) and
#   dolfinx.fem.forms.CompiledForm/dolfinx.plot's singledispatch
#   overload (conventionally named `_`): real objects that are either
#   not classes at all (a TypeVar is not a class) or have no page in
#   the generated API reference (neither is re-exported from a
#   documented module).
_any_role = r"py:(attr|class|data|func|meth|obj)"
nitpick_ignore_regex = [
    (_any_role, r"^numpy\.(u?int(8|16|32|64)|float(16|32|64)|complex(64|128))$"),
    (_any_role, r"^(numpy\.typing\.|npt\.)(NDArray|DTypeLike|ArrayLike)$"),
    (_any_role, r"^numpy\._typing\.[\w.]+\.(NDArray|DTypeLike|ArrayLike)$"),
    (_any_role, r"^np\.\w+$"),
    (_any_role, r"^_MPI\.\w+$"),
    (_any_role, r"^_sparse\.\w+$"),
    (_any_role, r"^PETSc\.(Vec|Mat)$"),
    # Sometimes split into a dangling prefix fragment by Sphinx's
    # signature parser when the bracketed dtype itself looks like an
    # identifier (e.g. `ndarray[dtype` on its own, `int32` separately).
    # nitpick_ignore_regex uses re.fullmatch, so the trailing `.*` must
    # be able to match zero characters too (no closing bracket).
    (_any_role, r"^(numpy\.)?ndarray\[.*"),
    (_any_role, r"^tuple\[.*\]$"),
    (_any_role, r"^(_cpp\.|dolfinx\.cpp\.)(fem|mesh|graph)\.\w+$"),
    (_any_role, r"^basix\._basixcpp\.FiniteElement_\w+$"),
    (_any_role, r"^basix\.ufl\._\w+$"),
    (_any_role, r"^dolfinx\.typing\.(Real|Scalar|Index)$"),
    (_any_role, r"^(Real|Scalar)$"),
    (_any_role, r"^PartitioningFunc$"),
    (_any_role, r"^dolfinx\.(la\._T|la\.superlu_dist\._T|fem\.petsc\._U)$"),
    (_any_role, r"^_EntityMap$"),
    (_any_role, r"^(dolfinx\.fem\.forms\.)?CompiledForm$"),
    (_any_role, r"^dolfinx\.plot\._$"),
]


def skip_member(app, what, name, obj, skip, opts):
    # Skip @entries from nanobind enums
    if name == "@entries":
        return True
    else:
        return skip


def setup(app):
    app.connect("autodoc-skip-member", skip_member)
