// Copyright (C) 2003-2006 Anders Logg.
// Licensed under the GNU LGPL Version 2.1.
//
// First added:  2003-05-26
// Last changed: 2006-03-01
//
// This file contains the contents of the index page
// for the documentation generated by doxygen.

/*! \mainpage DOLFIN Programmer's Reference
 *
 * This documentation is automatically generated each night for the current
 * development version of DOLFIN.
 *
 * <p>
 *
 * A good starting point is the <a href="inherits.html">graphical class hierarchy</a>. <p>
 */
