#!/usr/bin/env python

"""This script provides a benchmark for Extrapolation"""

# Copyright (C) 2010 Marie E. Rognes
#
# This file is part of DOLFIN.
#
# DOLFIN is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# DOLFIN is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with DOLFIN. If not, see <http://www.gnu.org/licenses/>.
#
# First added:  2010-06-07
# Last changed: 2013-06-17

from dolfin import *
from time import time

SIZE = 4

info("Extrapolation from P2*dP1 to P3*dP2 on UnitCubeMesh(%d, %d, %d)"
     % (SIZE, SIZE, SIZE))

mesh = UnitCubeMesh(SIZE, SIZE, SIZE)
cell = mesh.ufl_cell()

V = FunctionSpace(mesh, VectorElement("CG", cell, 2) * FiniteElement("DG", cell, 1))
W = FunctionSpace(mesh, VectorElement("CG", cell, 3) * FiniteElement("DG", cell, 2))

u = Expression(("sin(x[0])", "1.0", "x[0]*x[1]", "0.0"), degree=3)
u = interpolate(u, V)

w = Function(W)

tic = time()
w.extrapolate(u)
t = time() - tic

print "BENCH: ", t
