# Test environment for oneAPI compilers and Intel Python
name: macos-test-env
channels:
  - https://software.repos.intel.com/python/conda/
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - libblas
  - mpich
  - mpi4py
  - hdf5=*=mpi*
  - spdlog
  - pugixml
  - libboost-devel
  - nanobind
  - scikit-build-core
  - petsc
  - petsc4py
  - kahip
  - catch2
  - pytest
  - pytest-xdist
  - matplotlib
  - numba
  - cmake
  - ninja
  - pkg-config
  - pip
  - git
