#!/bin/sh
#
# Copyright (C) 2005-2007 Anders Logg.
# Licensed under the GNU LGPL Version 2.1.
#
# Recompile all ffc forms (use when FFC has been updated)
# This script should be run from the top level directory.

FORMFILES=`find src -name '*.form'`
TOPDIR=`pwd`

# Regenerate all forms in element and projection library
cd $TOPDIR/src/kernel/elements
python generate.py
python generate_projections.py

# Compile all form files
for FORMFILE in $FORMFILES; do

    echo "Compiling $FORMFILE"

    DIRNAME=`dirname $FORMFILE`
    FILENAME=`echo $FORMFILE | sed s#$DIRNAME/##`

    cd $TOPDIR/$DIRNAME
    ffc -s -l dolfin $FILENAME

done
