#!/bin/sh

# This script prepares and creates a .tar.gz package of
# the source tree. This should really be done with 'make dist'
# but until we get that working, this script does the job.

# Simple test to see where we are
# FIXME: Does not work when typing ./scripts/...
CHECK=`echo $0 | cut -d'/' -f1`
if [ "$CHECK" != "scripts" ]; then
    echo "This script must be run from the top level directory."
    exit 1
fi

# Get the version number
VERSION=`cat ./configure.ac | grep AC_INIT | cut -d ',' -f2 | cut -d' ' -f2`

# Write a message
echo Creating release $VERSION of DOLFIN, assuming this is a clean CVS version

# Create the directory
DISTDIR=dolfin-$VERSION
mkdir $DISTDIR

# Copy files
FILES=`ls | grep -v $DISTDIR`
cp -R $FILES $DISTDIR

# Remove unecessary files
REMOVE1=`find $DISTDIR | grep CVS`
REMOVE2=`find $DISTDIR -name '*~'`
REMOVE3=`find $DISTDIR -name '*.a'`
REMOVE4=$DISTDIR'/config.cache '$DISTDIR'/config.status '$DISTDIR'/config.log'
REMOVE5=`find $DISTDIR | grep '\.deps'`
REMOVE=$REMOVE1' '$REMOVE2' '$REMOVE3' '$REMOVE4' '$REMOVE5
rm -rf $REMOVE

# Create the archive
TARBALL='dolfin-'$VERSION'.tar.gz'
echo 'Creating arhive: '$TARBALL
tar zcf $TARBALL $DISTDIR

# Remove the directory
rm -rf $DISTDIR

# Unpack the tarball
echo 'Unpacking tarball to check if it compiles'
tar zxf $TARBALL

# Compile
echo 'Compiling in directory '$DISTDIR' (see make-'$VERSION'.log)'
MAKELOG='../make-'$VERSION'.log'
cd $DISTDIR
rm -f $MAKELOG
./configure.local --enable-debug >> $MAKELOG
make all install demo >& $MAKELOG

# Show log
less $MAKELOG

# Copy files to web server
cd ..
echo 'Copying ChangeLog to web server'
scp ChangeLog fenics@fenics.org:www.fenics.org/pub/software/dolfin
echo 'Copying TODO list to web server'
scp TODO fenics@fenics.org:www.fenics.org/pub/software/dolfin
echo 'Copying tarball to web server'
scp $TARBALL fenics@fenics.org:www.fenics.org/pub/software/dolfin/v0.5

# Update on web server
ssh fenics@fenics.org 'xterm -e emacs -nw www.fenics.org/dolfin/index.cpp'
ssh fenics@fenics.org 'xterm -e /home/fenics/local/bin/news'

# Notify dolfin-dev of the new version
SUBJECT="Version "$VERSION" of DOLFIN released"
cat ChangeLog | mail -s "$SUBJECT" dolfin-dev@fenics.org

# Write a message
echo ' '
echo 'Now update at freshmeat.'
