#!/bin/sh
#
# Copyright (c) Anders Logg 2002-2006
# Licensed under the GNU GPL Version 2
#
# This script creates a new release of DOLFIN

# Make sure we have the current version
echo '--- Synchronizing repository'
sleep 1
hg pull
hg update
hg commit
hg push default
echo '--- Repository synchronized, press return to continue'
read

# Update version number in ChangeLog
echo '--- Update version number in ChangeLog'
sleep 1
emacs -nw ChangeLog

# Update version number in configure.ac
echo '--- Update version number in configure.ac'
sleep 1
emacs -nw configure.ac

# Get the version number
VERSION=`cat ./configure.ac | grep AC_INIT | cut -d ',' -f2 | cut -d' ' -f2`
echo "--- Version number is $VERSION"
sleep 1

# Commit changes to hg
echo '--- Pushing changes to parent repository'
hg commit
hg push default
echo '--- Changes pushed, press return to continue'
read

# Write a message
echo "--- Creating release $VERSION of DOLFIN"

# Create the directory
DISTDIR=dolfin-$VERSION
echo "--- Creating directory release/$DISTDIR"
mkdir -p release
cd release
hg clone .. $DISTDIR
rm -r $DISTDIR/.hg
rm $DISTDIR/.hgignore

# Create the archive
TARBALL="dolfin-$VERSION.tar.gz"
echo "--- Creating arhive $TARBALL"
tar zcf $TARBALL $DISTDIR
cd ..

exit 0






# Create the directory
DISTDIR=dolfin-$VERSION
mkdir $DISTDIR

# Copy files
FILES=`ls | grep -v $DISTDIR`
cp -R $FILES $DISTDIR

# Remove unecessary files
REMOVE1=`find $DISTDIR | grep CVS`
REMOVE2=`find $DISTDIR -name '*~'`
REMOVE3=`find $DISTDIR -name '*.a'`
REMOVE4=$DISTDIR'/config.cache '$DISTDIR'/config.status '$DISTDIR'/config.log'
REMOVE5=`find $DISTDIR | grep '\.deps'`
REMOVE=$REMOVE1' '$REMOVE2' '$REMOVE3' '$REMOVE4' '$REMOVE5
rm -rf $REMOVE

# Create the archive
TARBALL='dolfin-'$VERSION'.tar.gz'
echo 'Creating arhive: '$TARBALL
tar zcf $TARBALL $DISTDIR

# Remove the directory
rm -rf $DISTDIR

# Unpack the tarball
echo 'Unpacking tarball to check if it compiles'
tar zxf $TARBALL

# Compile
echo 'Compiling in directory '$DISTDIR' (see make-'$VERSION'.log)'
MAKELOG='../make-'$VERSION'.log'
cd $DISTDIR
rm -f $MAKELOG
./configure.local --enable-debug >> $MAKELOG
export PATH=`pwd`"/local/bin:$PATH"
make all install demo >& $MAKELOG

# Show log
less $MAKELOG

# Copy files to web server
cd ..
echo 'Copying ChangeLog to web server'
scp ChangeLog fenics@fenics.org:www.fenics.org/pub/software/dolfin
echo 'Copying TODO list to web server'
scp TODO fenics@fenics.org:www.fenics.org/pub/software/dolfin
echo 'Copying tarball to web server'
scp $TARBALL fenics@fenics.org:www.fenics.org/pub/software/dolfin/v0.5

# Update on web server
ssh fenics@fenics.org 'xterm -e emacs -nw www.fenics.org/dolfin/index.cpp'
ssh fenics@fenics.org 'xterm -e /home/fenics/local/bin/news'

# Notify dolfin-dev of the new version
SUBJECT="Version "$VERSION" of DOLFIN released"
cat ChangeLog | mail -s "$SUBJECT" dolfin-dev@fenics.org

# Write a message
echo ' '
echo 'Now update at freshmeat.'
