spack:
  view: /opt/view
  config:
    install_tree:
      root: /opt/spack
      padded_length: 128

  packages:
    all:
      prefer:
      - "target=x86_64_v3 %oneapi@2025.2.0"

  # packages:
  #     all:
  #       require:
  #         - target=x86_64_v3 %oneapi
  #     gcc-runtime:
  #       require:
  #         - target=target=x86_64_v3 %gcc
  #     glibc:
  #       require:
  #         - target=target=x86_64_v3 %gcc

  mirrors:
    local-buildcache:
      url: oci://ghcr.io/fenics/spack-rocky-buildcache
      binary: true
      signed: false
      access_pair:
        id_variable: GITHUB_USER
        secret_variable: GITHUB_TOKEN

  # specs:
  # - petsc+mpi+mumps+shared %oneapi
  # - slepc %oneapi
  # - parmetis %oneapi
  # - pkgconfig
  # - python
  # - hdf5+mpi %oneapi
  # - boost %oneapi
  # - pugixml %oneapi
  # - spdlog %oneapi
  # - py-nanobind
  # - py-numpy %oneapi
  # - py-mpi4py %oneapi
  # - py-petsc4py
  # - py-slepc4py
  # - py-scikit-build-core+pyproject
  # - py-setuptools
  # - py-cffi
  # - py-pip
  # - cmake
  # - catch2
  # - py-pytest
  # - py-pytest-xdist
  # - ninja
