spack:
  view: /opt/view
  config:
    install_tree:
      root: /opt/spack
      padded_length: 128

  # packages:
  #   all:
  #     prefer:
  #       - "target=x86_64_v3 %oneapi"
  packages:
      all:
        require:
          - target=x86_64_v3 %oneapi
      gcc-runtime:
        require:
          - target=target=x86_64_v3 %gcc
      glibc:
        require:
          - target=target=x86_64_v3 %gcc

  mirrors:
    local-buildcache:
      url: oci://ghcr.io/fenics/spack-rocky-buildcache
      binary: true
      signed: false
      access_pair:
        id_variable: GITHUB_USER
        secret_variable: GITHUB_TOKEN
