#!/usr/bin/env python

__author__ = "Anders Logg (logg@simula.no)"
__date__ = "2009-09-15 -- 2009-09-17"
__copyright__ = "Copyright (C) 2009 Anders Logg"
__license__  = "GNU LGPL Version 2.1"

# Modified by Johan Hake, 2009.

# FIXME: Not checked if working!

from dolfin import *
from glob import glob
from numpy import arange

# Size of mesh
size = 32

# Number of processes to use
num_processes = 2**arange(6)

# Iterate over number of processes
t1 = []
t2 = []

for np in num_processes:
    print "Reading data from run with %d processes:"%np
    try:
        filename = glob("assemble-poisson_np_%d_size_%d*"%(np,size))[0]
    except:
        raise IOError, "Could not find: %s"%("assemble-poisson_np_%d_size_%d*"%(np,size))
    t1.append(float([line for line in open(filename).readlines() if "TIME:" in line][0].split("TIME: ")[-1]))
    try:
        filename = glob("solve-poisson_np_%d_size_%d*"%(np,size))[0]
    except:
        raise IOError, "Could not find: %s"%("solve-poisson_np_%d_size_%d*"%(np,size))
    t2.append(float([line for line in open(filename).readlines()  if "TIME:" in line][0].split("TIME: ")[-1]))

# Compute speedups
s1 = [t / t1[0] for t in t1]
s2 = [t / t2[0] for t in t2]

# Print results
table = Table("Speedup")
for i, np in enumerate(num_processes):
    table.set(str(np), "Assemble",         s1[i])
    table.set(str(np), "Assemble + solve", s2[i])

info(table, True)
