#!/usr/bin/env python

__author__ = "Anders Logg (logg@simula.no)"
__date__ = "2009-09-15 -- 2009-09-17"
__copyright__ = "Copyright (C) 2009 Anders Logg"
__license__  = "GNU LGPL Version 2.1"

# modified by Johan Hake 2009

from dolfin_utils.pjobs import submit
from numpy import arange
import sys

# Size of mesh
size = 32

# Number of processes to use
num_processes = 2**arange(6)

dryrun = True if 'dryrun' in sys.argv else False

for np in num_processes:
    if np ==1:
        run_cmd = ""
    else:
        run_cmd = "mpirun.openmpi -n %d "%np
    submit("%s./assemble-poisson %d"%(run_cmd,size),nodes=max(1,np/8),ppn=8, name = "assemble-poisson_np_%d_size_%d"%(np,size),dryrun=dryrun)
    submit("%s./solve-poisson %d"%(run_cmd,size),nodes=max(1,np/8),ppn=8, name = "solve-poisson_np_%d_size_%d"%(np,size),dryrun=dryrun)
