// Copyright (C) 2003-2005 Anders Logg.
// Licensed under the GNU GPL Version 2.
//
// First added:  2003-05-26
// Last changed: 2005
//
// This file contains the contents of the index page
// for the documentation generated by doxygen.

/*! \mainpage DOLFIN Programmer's Reference
 *
 * This documentation is automatically generated each night for the latest cvs version of
 * DOLFIN using the excellent tool <a href="http://www.doxygen.org/">Doxygen</a>. <p>
 * 
 * Follow the links above to browse the documentation. If you're new to DOLFIN, a good 
 * starting point may be to take a look at the graphical <a href="inherits.html">class hierarchy</a>. <p>
 */
