#!/bin/sh
#
# Copyright (C) 2006 Anders Logg
#
# This file is part of DOLFIN.
#
# DOLFIN is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# DOLFIN is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with DOLFIN.  If not, see <http://www.gnu.org/licenses/>.
#
# Convert all DOLFIN XML files in a directory from
# the old DOLFIN XML format to the new format

# Unpack all .xml.gz files if any
for f in *.xml.gz; do
	echo "Unpacking $f..."
	gunzip $f
done

# Convert all .xml files
for f in *.xml; do
	echo "Converting $f..."
	mv $f $f.old
	dolfin-convert -i xml-old $f.old $f
done

# Pack all .xml files
for f in *.xml; do
	echo "Packing $f..."
	gzip $f
done
