SET(DOLFIN_BOOST_INCLUDE_DIR "" CACHE PATH "Override the default location for Boost header files.")
SET(DOLFIN_BOOST_LIBRARY_DIR "" CACHE PATH "Override the default location for Boost libraries.")
SET(DOLFIN_BOOST_USE_MULTITHREADED OFF CACHE BOOL "Use multithreaded Boost libraries.")

SET(BOOST_INCLUDEDIR ${DOLFIN_BOOST_INCLUDE_DIR})
SET(BOOST_LIBRARYDIR ${DOLFIN_BOOST_LIBRARY_DIR})
SET(Boost_ADDITIONAL_VERSIONS 1.43 1.43.0)
SET(Boost_USE_MULTITHREADED ${DOLFIN_BOOST_USE_MULTITHREADED})
FIND_PACKAGE(Boost 1.34 COMPONENTS ${DOLFIN_BOOST_COMPONENTS} REQUIRED)
