set(DOLFIN_LIBXML2_FOUND 0)

find_package(LibXml2 REQUIRED)

if(LIBXML2_FOUND)
  set(DOLFIN_LIBXML2_INCLUDE_DIR
    ${LIBXML2_INCLUDE_DIR}
    )

  set(DOLFIN_LIBXML2_LIBRARIES
    ${LIBXML2_LIBRARIES}
    )

  set(DOLFIN_LIBXML2_FOUND 1)
endif(LIBXML2_FOUND)
