#!/usr/bin/env python

import sys

if not len(sys.argv) == 2:
    print "Usage: plot_partitions n"
    sys.exit(1)
num_partitions = int(sys.argv[1])

from dolfin import *

for i in range(num_partitions):
    mesh = Mesh("unitsquare-%d.xml" % i)
    plot(mesh, title="Partition %d" % i)

interactive()
