#!/usr/bin/env python
#
# Copyright (C) 2009 Anders Logg
# Licensed under the GNU LGPL Version 2.1
#
# Simple script for mesh STL geometry with TetGen and converting to DOLFIN XML format

import sys, os

# Check command-line arguments
if len(sys.argv) != 3:
    print "Usage: dolfin-tetgen mesh.stl mesh.xml"
    sys.exit(1)
stl_file = sys.argv[1]
xml_file = sys.argv[2]

# Run TetGen
os.system("tetgen -g -p %s" % stl_file)

# Convert to DOLFIN
mesh_file = stl_file.split(".stl")[0] + ".1" + ".mesh"
os.system("dolfin-convert %s %s" % (mesh_file, xml_file))
