name: CI Docker build environment images
# Builds the fenicsproject/test-env and dolfinx/dev-env images once per week.
# These are used for build/test workflows and end-user builds of DOLFINX,
# respectively.

on:
  # Uncomment the below to trigger 'docker build' on push
  #push:
  #  branches:
  #    - "**"
  schedule:
    # '*' is a special character in YAML, so string must be quoted
    - cron: "0 1 * * MON"

jobs:
  build_test_env:
    name: Build fenicsproject/test-env image
    if: github.repository == 'FEniCS/dolfinx'
    if: github.ref == 'master'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build --file .github/workflows/Dockerfile --target test --tag fenicsproject/test-env .
      - name: Log into the DockerHub registry
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Push to the DockerHub registry
        run: docker push fenicsproject/test-env

  build_dev_env:
    name: Build dolfinx/dev-env image
    if: github.repository == 'FEniCS/dolfinx'
    if: github.ref == 'master'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build --file docker/Dockerfile --target dev-env --tag dolfinx/dev-env .
      - name: Log into the DockerHub registry
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Push to the DockerHub registry
        run: docker push dolfinx/dev-env
